import type { OpenEditorTheme } from "@openeditor/react";

export const baseBlocksOpenEditorTheme = {
  surface: "var(--background)",
  surfaceRaised:
    "color-mix(in oklab, var(--background) 94%, var(--foreground))",
  surfaceMuted: "var(--muted)",
  blockSurface: "var(--card)",
  text: "var(--foreground)",
  textSoft: "var(--foreground)",
  heading: "var(--foreground)",
  muted: "var(--muted-foreground)",
  placeholder: "var(--muted-foreground)",
  border: "var(--border)",
  borderStrong: "var(--input)",
  structuralLine: "var(--border)",
  accent: "var(--accent)",
  accentText: "var(--accent-foreground)",
  accentStrong: "var(--primary)",
  buttonBackground: "var(--primary)",
  buttonText: "var(--primary-foreground)",
  codeBackground: "var(--card)",
  codeText: "var(--foreground)",
  link: "var(--primary)",
  linkHover: "var(--foreground)",
  shadow: "color-mix(in oklab, var(--foreground) 14%, transparent)",
  fontSans: "inherit",
  radiusSmall: "0.5rem",
  radiusMedium: "0.75rem",
  radiusLarge: "1rem",
  spaceBlock: "1rem",
  spaceInline: "1rem",
} satisfies OpenEditorTheme;
